version: '2.1'

services:
   ngnx:
     image: nginx:latest
     restart: always
     build:
       context: ./dockerfiles
       dockerfile: Dockerfile.nginx
       args:
         NGINX_CONF: ${NGINX_CONF}
     ports:
       - ${IP_EXT}:80:80
     depends_on:
       - app

   app:
     image: petclinic:latest
     restart: always
     build:
       context: ./dockerfiles
       dockerfile: Dockerfile.app
     depends_on:
       db:
         condition: service_healthy
     volumes:
     - m2:/root/.m2

   db:
     image: mysql:5.7.8
     restart: always
     ports:
       - ${IP_INT}:3306:3306 # change ip if required
     volumes:
     - ./conf/mysql:/docker-entrypoint-initdb.d
     - /opt/petclinic/db_data:/var/lib/mysql
     environment:
        MYSQL_DATABASE: petclinic
        MYSQL_ROOT_PASSWORD: petclinic
     healthcheck:
       test: "/usr/bin/mysql -u root -h db --password=\"petclinic\" -e \"show databases;\""
       interval: 5s
       timeout: 5s
       retries: 5

volumes:
   db_data:
   m2:






