version: '2.1'

services:
   ngnx:
     image: nginx:latest
     build:
       context: ./dockerfiles
       dockerfile: Dockerfile.nginx
       args:
         NGINX_CONF: ${NGINX_CONF}
     ports:
       - 10.0.2.15:80:80
     depends_on:
       - app

   app:
     image: petclinic:latest
     build:
       context: ./dockerfiles
       dockerfile: Dockerfile.app
     depends_on:
       db:
         condition: service_healthy

   db:
     image: mysql:5.7.8
     ports:
       - 10.0.2.15:3306:3306 # change ip if required
     volumes:
      - ./conf/mysql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
     environment:
        MYSQL_DATABASE: petclinic
        MYSQL_ROOT_PASSWORD: petclinic
     healthcheck:
       test: "/usr/bin/mysql -u root -h db --password=\"petclinic\" -e \"show databases;\""
       interval: 5s
       timeout: 5s
       retries: 5

volumes:
   db_data:

