version: '3'

services:
   ngnx:
     image: nginx:latest
     ports:
       - 10.0.2.15:80:80
     depends_on:
       - app

   app:
     image: petclinic:latest
     depends_on:
       - db

   db:
     image: mysql:5.7.8
     ports:
       - 10.0.2.15:3306:3306 # change ip if required
     volumes:
      - ./conf/mysql:/docker-entrypoint-initdb.d
      - db_data:/var/lib/mysql
     environment:
        MYSQL_DATABASE: petclinic
        MYSQL_ROOT_PASSWORD: petclinic

volumes:
   db_data:

