FROM centos:7 as nginx
ARG NGINX_CONF

RUN yum install --nogpgcheck -y epel-release &&\
    yum install --nogpgcheck -y nginx &&\
    mv -v /etc/nginx/nginx.conf /etc/nginx/nginx.conf.bak &&\
    echo "$NGINX_CONF" > /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]






